--
--		Nombre: Generar medios electrónicos Documento Soporte mediante JSON (DTO) via API Rest - Saphety Colombia.
--
--		Autor: Nicolás David Cubillos
--
--		Contenido: Generar medios electrónicos Documento Soporte mediante JSON (DTO) - Saphety Colombia.
--
--		Fecha: 7 de agosto de 2022.
--


USE AJOVECO
GO

DROP FUNCTION [dbo].[DS_DOCUMENTOSSOPORTEENVIAR]
GO
DROP FUNCTION [dbo].[DS_DATOSPROVEEDOR]
GO
DROP FUNCTION [dbo].[DS_DETALLEDCTO]
GO

/*
	Función DS_DOCUMENTOSSOPORTEENVIAR
	Retorna la lista de Documento(s) Doporte a enviar en un periodo dado
	
	SELECT * FROM DS_DOCUMENTOSSOPORTEENVIAR('20200101', '20220101')
*/

CREATE FUNCTION [dbo].[DS_DOCUMENTOSSOPORTEENVIAR]
(
@fecha1 date,
@fecha2 date
)
Returns Table
as
Return
(
SELECT
1 AS ENVIO,
CASE WHEN T.OTRAMON = 'S' THEN 'USD' ELSE 'COP' END MONEDA,
T.TIPODCTO, 
T.NRODCTO,
CAST(FORMAT(T.FECHA, 'yyyy-MM-dd') AS CHAR) FECHA,
T.NIT,
T.NOTA,
MV.NETO,
T.PASSWORDIN
FROM
TRADE T,
VCOMERCOM MV
WHERE 
T.TIPODCTO = 'DS' AND
MV.TIPODCTO = T.TIPODCTO AND
T.NRODCTO = MV.NRODCTO AND
T.MEUUID = '' AND
T.FECHA BETWEEN @fecha1 AND @fecha2
)


/*
	Función VS_DATOSPROVEEDOR
	Retorna la información del proveedor del Documento Soporte.
	
	SELECT * FROM DS_DATOSPROVEEDOR('444444304-0')
*/

GO

CREATE FUNCTION [dbo].[DS_DATOSPROVEEDOR]
(
@nit char(500)
)
Returns Table
as
Return
(
SELECT 
PROV.NOMBRE,
PROV.CDCIIU,
PROV.DIRECCION,
PROV.EMAILP,
PROV.CODPOSTAL,
PAISES.ISO_3166_1 CODPAIS
FROM
MTPROCLI PROV,
MTPAISES PAISES
WHERE 
NIT = @nit AND
PROV.PAIS = PAISES.CODIGO
)

/*
	Función DS_DETALLEDCTO
	Retorna la información del proveedor del Documento Soporte.
	
	SELECT * FROM DS_DETALLEDCTO('DS', 565)
*/

GO

CREATE FUNCTION [dbo].[DS_DETALLEDCTO]
(
@TIPODCTO CHAR (50),
@NRODCTO CHAR (50)
)
Returns Table
as
Return
(
SELECT
PRODUCTO,
CANTIDAD,
NOMBRE NOMBRE_PRODUCTO,
IVA PORCENTAJE_IVA,
TARIVA TARIFA_IVA,
(SELECT UNIDINT FROM MTUNIDAD WHERE UNIDAD = MVTRADE.UNDVENTA) UNIDAD_MEDIDA,
CASE WHEN VALORUNIT > 0
THEN VALORUNIT
ELSE XVALORUN
END VALOR_UNITARIO,
CASE WHEN VALORUNIT > 0 
THEN CANTIDAD * VALORUNIT
ELSE CANTIDAD * XVALORUN
END VALOR_PRODUCTOS,
CASE WHEN VALORUNIT > 0
THEN CANTIDAD * VALORUNIT * DESCUENTO
ELSE CANTIDAD * XVALORUN * DESCUENTO
END DESCUENTO,
CASE WHEN VALORUNIT > 0
THEN (CANTIDAD * VALORUNIT) - (CANTIDAD * VALORUNIT * DESCUENTO)
ELSE (CANTIDAD * XVALORUN) - (CANTIDAD * XVALORUN * DESCUENTO)
END BASE_GRAVABLE,
CASE WHEN VALORUNIT > 0
THEN ((CANTIDAD * VALORUNIT) - (CANTIDAD * VALORUNIT * DESCUENTO)) * IVA / 100
ELSE ((CANTIDAD * XVALORUN) - (CANTIDAD * XVALORUN * DESCUENTO)) * IVA / 100
END VALOR_IVA,
CASE WHEN VALORUNIT > 0
THEN ((CANTIDAD * VALORUNIT) - (CANTIDAD * VALORUNIT * DESCUENTO)) * PORETE / 100
ELSE ((CANTIDAD * XVALORUN) - (CANTIDAD * XVALORUN * DESCUENTO)) * PORETE / 100
END VALOR_RTEFTE,
CASE WHEN VALORUNIT > 0
THEN ((CANTIDAD * VALORUNIT) - (CANTIDAD * VALORUNIT * DESCUENTO)) * PORICA / 100
ELSE ((CANTIDAD * XVALORUN) - (CANTIDAD * XVALORUN * DESCUENTO)) * PORICA / 100
END VALOR_RTEICA,
CASE WHEN VALORUNIT > 0
THEN ((CANTIDAD * VALORUNIT) - ((CANTIDAD * VALORUNIT) * DESCUENTO)) + (((CANTIDAD * VALORUNIT) - ((CANTIDAD * VALORUNIT) * DESCUENTO)) * IVA / 100) - (((CANTIDAD * VALORUNIT) - ((CANTIDAD * VALORUNIT) * DESCUENTO)) * PORETE / 100) - (((CANTIDAD * VALORUNIT) - ((CANTIDAD * VALORUNIT) * DESCUENTO)) * PORICA / 100)
ELSE ((CANTIDAD * XVALORUN) - ((CANTIDAD * XVALORUN) * DESCUENTO)) + (((CANTIDAD * XVALORUN) - ((CANTIDAD * XVALORUN) * DESCUENTO)) * IVA / 100) - (((CANTIDAD * XVALORUN) - ((CANTIDAD * XVALORUN) * DESCUENTO)) * PORETE / 100) - (((CANTIDAD * XVALORUN) - ((CANTIDAD * XVALORUN) * DESCUENTO)) * PORICA / 100)
END VALOR_NETO,
PORETE PORCENTAJE_RTEFTE
FROM
MVTRADE
WHERE
TIPODCTO = @TIPODCTO AND
NRODCTO = @NRODCTO
)